# Generated by Django 5.0.7 on 2024-07-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctors_dep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors'),
        ),
    ]
