# Generated by Django 5.0.7 on 2024-07-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_booked_on_alter_booking_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_image',
            field=models.ImageField(default='departments/defulat_image.jpg', upload_to='departments/'),
            preserve_default=False,
        ),
    ]
